version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/nodes"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
  - package-ecosystem: "cargo"
    directory: "/dynmap"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    directory: "/dynmap"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
